apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    release.openshift.io/create-only: "true"
  creationTimestamp: "2020-02-20T11:28:24Z"
  generation: 2
  name: cluster
  resourceVersion: "192680"
  selfLink: /apis/config.openshift.io/v1/oauths/cluster
  uid: 1b0a6f66-53d4-11ea-8d13-023d211f3248
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: htp-secret
    mappingMethod: claim
    name: myusers
    type: HTPasswd
